name: Auto PR Creator

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Python script
        run: |
          mkdir -p scripts
          echo "def add(a, b): return a + b" > scripts/addition.py
          echo "if __name__ == '__main__': print(add(2, 3))" >> scripts/addition.py

      - name: Commit and push
        run: |
          BRANCH=find-target-pr-$(date +%s)
          git checkout -b $BRANCH
          git add scripts/addition.py
          git commit -m "Add addition script"
          git push origin $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR - Addition Script"
          body: "This PR adds a simple addition Python script."
          base: main
          branch: ${{ env.BRANCH }}
