name: Auto Code PR

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create changes
        run: |
          mkdir -p scripts
          echo "print('Hello from GitHub Actions!')" > scripts/hello.py

      - name: Commit and push changes
        run: |
          git checkout -b auto-pr-branch
          git add scripts/hello.py
          git commit -m "chore: add hello.py"
          git push origin auto-pr-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR: Add hello.py"
          body: "This PR was created automatically by a GitHub Action."
          head: auto-pr-branch
          base: main
