name: Auto PR - Hello World Script

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Hello World Python script
        run: |
          mkdir -p hello
          echo "print('Hello, World!')" > hello/hello_world.py

      - name: Commit and push to new branch
        run: |
          BRANCH=hello-world-pr-$(date +%s)
          git checkout -b $BRANCH
          git add hello/hello_world.py
          git commit -m "Add hello world script"
          git push origin $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR - Hello World Script"
          body: "This PR adds a basic Hello World Python script."
          base: main
          branch: ${{ env.BRANCH }}
